apiVersion: batch/v1
kind: Job
metadata:
  name: sysbench
spec:
  completions: 500
  parallelism: 500
  template:
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      initContainers:
      - name: prepare
        image: juanlee/sysbench:latest
        imagePullPolicy: Always
        command:
        - /sysbench
        - fileio 
        - prepare
        - --file-test-mode=rndrw
        volumeMounts:
        - mountPath: /working
          name: fileio-volume
      containers:
      - name: sysbench
        image: juanlee/sysbench:latest
        imagePullPolicy: Always
        command:
        - /sysbench
        - fileio 
        - run
        - --file-test-mode=rndrw
        - --events=100000
        - --time=0
        resources:
          requests:
            cpu: 100m
            memory: 2Gi
          limits:
            cpu: 1
            memory: 2Gi
        volumeMounts:
        - mountPath: /working
          name: fileio-volume
      volumes:
      - name: fileio-volume
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 256Gi
              storageClassName: managed-csi-premium
      restartPolicy: Never
  backoffLimit: 100
