apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: autoscale
  namespace: tekton
spec:
  timeout: 3h
  params:
  - name: sku-tier
    value: "Paid"
  - name: network-plugin
    value: "azure"
  - name: node-vm-size
    value: "Standard_d4s_v3"
  - name: node-osdisk-type
    value: "Managed"
  - name: node-osdisk-size
    value: "50"
  pipelineRef:
    name: autoscale
  serviceAccountName: azure-identity
