apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cron-listener
spec:
  serviceAccountName: cron-listener
  triggers:
    - name: cron-trigger
      bindings:
      - ref: cron-binding
      template:
        ref: pipeline-template
