apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: az-aks-delete
spec:
  params:
  - name: cluster-name
    type: string
  - name: resource-group
    type: string
  - name: node-count
    type: string
    default: ""
  - name: az-image
    description: Azure CLI container image to run this task
    default: mcr.microsoft.com/azure-cli:latest
  stepTemplate:
    env:
    - name: "AZURE_CONFIG_DIR"
      value: "/workspace/.azure"
  steps:
  - name: az-login
    image: "$(params.az-image)"
    script: |
      #!/usr/bin/env bash

      mkdir -p "${AZURE_CONFIG_DIR}"
      az login \
        --service-principal \
        -t $AZURE_TENANT_ID \
        -u $AZURE_CLIENT_ID \
        --federated-token $(cat $AZURE_FEDERATED_TOKEN_FILE) \
        -o yaml
  - name: az-aks-scale
    image: "$(params.az-image)"
    script: |
      #!/usr/bin/env bash
      if [[ "$(params.node-count)" != "" ]]; then
        az aks scale -g $(params.resource-group) -n $(params.cluster-name) -c $(params.node-count) --verbose -o yaml
      fi
  - name: az-aks-delete
    image: "$(params.az-image)"
    script: |
      #!/usr/bin/env bash
      az aks delete -g $(params.resource-group) -n $(params.cluster-name) --verbose -o yaml --yes
