apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: az-aks-upgrade
spec:
  params:
  - name: cluster-name
    type: string
  - name: resource-group
    type: string
  - name: kubernetes-version
    type: string
  - name: az-image
    description: Azure CLI container image to run this task
    default: mcr.microsoft.com/azure-cli:latest
  stepTemplate:
    env:
    - name: "AZURE_CONFIG_DIR"
      value: "/workspace/.azure"
  steps:
  - name: az-login
    image: "$(params.az-image)"
    script: |
      #!/usr/bin/env bash

      mkdir -p "${AZURE_CONFIG_DIR}"
      az login \
        --service-principal \
        -t $AZURE_TENANT_ID \
        -u $AZURE_CLIENT_ID \
        --federated-token $(cat $AZURE_FEDERATED_TOKEN_FILE) \
        -o yaml
  - name: az-aks-upgrade
    image: "$(params.az-image)"
    script: |
      #!/usr/bin/env bash

      az aks upgrade -g $(params.resource-group) -n $(params.cluster-name) \
        --kubernetes-version $(params.kubernetes-version) \
        --debug --verbose --yes
