apiVersion: v1
kind: Service
metadata:
  labels:
    component: kube-proxy
  name: kube-proxy
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP
    targetPort: 10249
  sessionAffinity: None
  type: ClusterIP
  selector:
    component: kube-proxy
