apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../bases/kube-prometheus
- coredns-prometheusRule.yaml
- kube-proxy-service.yaml
- kubeProxy-prometheusRule.yaml
- kubernetes-serviceMonitorKubeProxy.yaml

patchesStrategicMerge:
- alertmanager-main_patch.yaml
- kubernetes-serviceMonitorCoreDNS_patch.yaml
- resources_patch.yaml

patches:
- path: daemonset-tolerations_patch.yaml
  target:
    kind: DaemonSet
- path: deploy-tolerations_patch.yaml
  target:
    kind: Deployment
- path: prometheus-tolerations_patch.yaml
  target:
    kind: Prometheus
- path: alertmanager-tolerations_patch.yaml
  target:
    kind: Alertmanager
