apiVersion: v1
kind: Service
metadata:
  name: trow-svc
spec:
  ports:
  - name: http-tcp
    protocol: TCP
    port: 8000
    targetPort: trow-http-port
    nodePort: 31000
  - name: https-tcp
    protocol: TCP
    port: 8443
    targetPort: trow-https-port
    nodePort: 31001
