apiVersion: batch/v1
kind: Job
metadata:
  generateName: stressful
spec:
  completions: 50
  parallelism: 50
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
      - name: stressful
        image: localhost:31000/f/docker/juanlee/stressful:trow
        imagePullPolicy: Always
        command: ["/stress-ng",  "--cpu", "1", "--io", "1", "--hdd", "1", "--vm", "1", "--vm-bytes", "1G", "--timeout", "2m", "-v", "--metrics"]
        resources:
          requests:
            cpu: 100m
            memory: 2Gi
          limits:
            cpu: 1
            memory: 4Gi
      restartPolicy: Never
  backoffLimit: 4
