apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kbench
spec:
  type: git
  params:
    - name: url
      value: https://github.com/juan-lee/k-bench
    - name: revision
      value: master
