apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knative-system

resources:
- namespace.yaml
- https://github.com/knative/operator/releases/download/knative-v1.2.0/operator.yaml
