apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knative-serving

resources:
- namespace.yaml
- https://github.com/knative/serving/releases/download/knative-v1.2.0/serving-default-domain.yaml
- knative-serving.yaml
